language: python
python: 2.7
install:
    - pip install tox
    - pip install coveralls
script:
    - tox
    - coverage run --omit=pscan/tests/*,pscan/__main__.py --source=pscan setup.py test
after_success:
    - coveralls
